### ISSUE TITLE
iOS 17 Snapshots have weird edges

### ISSUE THREAD

**Issue by davidalhambra** [pointfreeco/swift-snapshot-testing#790]
**Describe the bug**
When I run my tests on iOS17 I get different version than the previous versions. It's weir because the components itself doesn't change visually on my app, only in the snapshots. It happens with some components that have radius or curved edges.
This is happening for UIKit and SwiftUI components. They also have different approaches. In the screenshot we see an screenshot of one Capsule SwiftUI item, but is happening the same with an UIKit item built with a background color and shaped.

**To Reproduce**
This is the body of the Capsule item of the screenshot bellow.
```swift
        public var body: some View {
            /// We do not use Apples formatted API because we want a small badge
            /// without a space between number and % - also this code looks simpler.
            Text(String(format: "%.0f%%", progress))
                .padding(.horizontal, Style.horizontalPadding)
                .frame(height: Style.height)
                .background(
                    Capsule()
                        .fill(Style.background(for: progress).color,
                              strokeBorder: Style.border.color,
                              lineWidth: Style.borderWidth)
                )
        }
```

**Expected behavior**
On previous iOS versions we had a clear Snapshot with the Capsule or Circle shape. Right now we get the good shape on the app (nothing changed) but not at the Snapshot.

**Screenshots**
<img width="375" alt="test_SwiftUI_ProgressBadge_ColorSchemes light" src="https://github.com/pointfreeco/swift-snapshot-testing/assets/40705826/1a0f59bc-fbe8-489a-bbc6-1048ec8345cd">

<img width="752" alt="Captura de pantalla 2023-10-11 a las 14 27 08" src="https://github.com/pointfreeco/swift-snapshot-testing/assets/40705826/7d5b53db-d8c9-4223-b5e7-056858617057">

**Environment**
  - swift-snapshot-testing version [e.g. 1.9.0]
  - Xcode 15.0
  - Swift 5
  - OS: iOS 17

**Comment by davidaberg** [comment]
We are also getting jagged and blurry border edges when recording snapshots in Xcode 15 / iOS 17. Only in the snapshots, not in our app.

**Comment by renate-wuenschl** [comment]
From what I can see the issue seems to be related to any kind of RoundedRectangle in SwiftUI with a border (also SwiftUI.Toggle).

Side note: Recently SnapshotTesting was crashing for me when changing my own uneven rectangle implementation to apples UnevenRoundedRectangle() - maybe this is related 🤷🏻‍♀️

**Comment by lukeredpath** [comment]
I fixed this issue by explicitly using a `circular` corner style - on iOS 17 I think it now defaults to `continuous`.

**Comment by ChrisMash** [comment]
I'm seeing this on Xcode 16 / iOS 18 with UIKit buttons now 😬

**Comment by josh-arnold-1** [comment]
I'm not sure if its just me, but it seems using a corner radius of `16` seems to work fine. I wonder if using a power of `2` or power of `4` as a value works fine?

I think for UIKit, if you manually mask your view using a `UIBezierPath`, it seems to work as well as a possible solution to using `cornerRadius`.

**Comment by paulomendes** [comment]
I'm still having this issue on Xcode 16 and tvOS 18. Using `.continuous` style didn't work for me .
